name: Build Android APK (Buildozer)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python (for buildozer action)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Buildozer to build APK
        uses: digreatbrian/buildozer-action@v1
        with:
          buildozer-cmd: "android debug"
          python-version: "3.10"
          work-dir: "."

      - name: Find APKs
        run: |
          echo "Listing .apk files:"
          find $GITHUB_WORKSPACE -type f -name "*.apk" -print || true
          ls -la

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: |
            **/*.apk
