name: Build Android APK (Manual Buildozer Setup)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip \
            python3-setuptools \
            python3-dev \
            git \
            zip \
            openjdk-17-jdk \
            unzip \
            curl \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libncurses6

      - name: Install Buildozer
        run: |
          pip3 install --upgrade pip
          pip3 install cython
          pip3 install buildozer

      - name: Install Android SDK/NDK
        run: |
          sudo mkdir -p /opt/android/cmdline-tools/latest
          cd /opt/android/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools/latest .
          export ANDROID_HOME=/opt/android
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bi_
